### ISSUE TITLE
bbp_hetero uncertainties plot 

### ISSUE THREAD

**Issue by caxelrud** [JavierAntoran/Bayesian-Neural-Networks#10]
For the bbp_hetero notebook, should be plot be done as:
plt.fill_between(np.linspace(-5, 5, 200)* x_std + x_mean, means **- aleatoric**, means **+ aleatoric**, color = c[0], alpha = 0.3, label = 'Aleatoric')
plt.fill_between(np.linspace(-5, 5, 200)* x_std + x_mean, means **- epistemic**, means **+ epistemic**, color = c[1], alpha = 0.3, label = 'Epistemic')

At the moment, the boundaries are mixed.

Thanks for the attention so far, 
Celso

**Comment by JavierAntoran** [comment]
thanks! will take a look soon.

**Comment by stratisMarkou** [comment]
Thanks for flagging this up, the way we plot the uncertainties may not be completely clear, so here is an explanation.

Often, people plot the total uncertainty in the network's predictions, but that obscures how much of that uncertainty is aleatoric and how much is epistemic. We could have chosen to plot two envelopes, namely (mean +/- aleatoric) and (mean +/- epistemic) as you say, to make the size of each source clear. But this would be at a cost of the total uncertainty being less clear, because those +/- envelopes correspond to purely the epistemic and aleatoric sources, whereas the total uncertainty is sqrt(aleatoric ^ 2 + epistemic ^ 2). Instead, we decided to plot (mean +/- aleatoric) and (mean +/- total), colouring the aleatoric uncertainty orange and the region between the aleatoric and the total uncertainty as blue.

Of course our method has its own drawback, because if the uncertainties have significantly different sizes, the the root-of-sum-of-squares will be approximately equal to the larger uncertainty and the plot will again be a bit misleading.

Perhaps a good idea would be to plot three envelopes: epistemic, aleatoric and total; but that will also make the plots more cluttered. Ultimately it's just a plotting convention. If you have an idea to make the plots clearer, let us know or even better make a PR.

Thanks for bringing this up :)
